# Generated by Django 3.1.5 on 2021-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210111_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='by_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
