# Generated by Django 3.1.5 on 2021-02-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210202_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём памяти'),
        ),
    ]
