# Generated by Django 3.1.5 on 2021-02-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210203_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='by_anonymous_user',
            new_name='for_anonymous_user',
        ),
    ]
